### ISSUE TITLE
Typo in NodeJS course

### ISSUE THREAD

**Issue by zeshhaan** [MicrosoftDocs/node-essentials#10]
Hi,
I wanted to let you know there is a typo in the _file system_ module, [unit 3](https://docs.microsoft.com/en-gb/learn/modules/nodejs-files/3-exercise-file-system) where a function name is mistyped in step 3 of "**Write a method to find the sales.json files**"

It is written as 

> This new method findFiles is created inside the main **`findSalesMethod`** method so that it can run as many times as necessary to find all the sales files and populate the salesFiles array. The folderName value is the path to the current folder.

Instead it should be

> This new method findFiles is created inside the main **`findSalesFiles`** method so that it can run as many times as necessary to find all the sales files and populate the salesFiles array. The folderName value is the path to the current folder.

[Loom video link](https://www.loom.com/share/0f1da314b4664a89a55ca4bf8d01b7ae)

**Comment by xgqfrms** [comment]
https://learn.microsoft.com/en-gb/training/modules/nodejs-files/3-exercise-file-system
