### ISSUE TITLE
Recommended code for exercise doesn't work

### ISSUE THREAD

**Issue by d-tenorio** [MicrosoftDocs/node-essentials#4]
The code provided for app.delete on **Exercise - Route management -> Implement support for reading and writing data -> 7.** will not work with the files provided. Recommend changing to:

```js
app.delete('/products', function(req, res) {
  const deletedProduct = products.find(p => p.id === +req.body.id);
  products = products.filter(p => p.id !== +req.body.id);
  res.json(deletedProduct);
});
```

**Comment by sinedied** [comment]
Thanks for reporting, we'll take a look at that.

**Comment by softchris** [comment]
1) The idea of this exercise is two-fold, first show how you an delete with a param through the route (to delete the entry use the `nodejs-http/exercise-express-routing/reading-writing/client-delete.js`)... 
2) The second exercise using `route()` is using the body instead, to delete such an entry use the `https://github.com/MicrosoftDocs/node-essentials/blob/main/nodejs-http/exercise-express-routing/reading-writing/client-delete-route.js` file instead ... 

- `client-delete.js` has been changed as it previously did not support deletion through route param.
- `client-delete-route.js` has been added to the repo.

All files are there and should work, so no changes needed. Closing this issue @sinedied
