### ISSUE TITLE
Missing `client-delete-route.js` from repo

### ISSUE THREAD

**Issue by hereswhatidid** [MicrosoftDocs/node-essentials#6]
In step 5 of the Route management lesson there is a reference to 'client-delete-route.js'. This file does not appear to exist within the repo which makes it impossible to complete the tasks on that step.

Here is the page that has the reference:

https://docs.microsoft.com/en-us/learn/modules/build-web-api-nodejs-express/5-exercise-route-management

And the path to where the file should exist:

/node-essentials/node-dependencies/8-express-app/node-essentials/nodejs-http/exercise-express-routing/reading-writing/client-delete-route.js

**Comment by softchris** [comment]
It's here @hereswhatidid node-essentials/nodejs-http/exercise-express-routing/reading-writing/client-delete.js
